### ISSUE TITLE
Default argument

### ISSUE THREAD

**Issue by PatMyron** [cclauss/GitHub-Action-for-pylint#1]
The default argument in the README fails:
`args = "pylint"`
https://github.com/PatMyron/advent-of-code/runs/76464535

It'd be even better if no argument had to be provided at all

**Comment by cclauss** [comment]
I updated README.md to demonstrate _pip install -r requirements.txt_ but pylint still _needs to be told_ which directories to work on ("*2" in your case) which is different from all other linters that I use.

**Comment by PatMyron** [comment]
I'm wondering if there is something analogous to `pylint **/*.py` that would work as a sensible default

https://stackoverflow.com/questions/36873096/how-to-run-pylint-for-all-python-files-in-a-directory

Seems to work for me
