### ISSUE TITLE
e0401: unable to import

### ISSUE THREAD

**Issue by PatMyron** [cclauss/GitHub-Action-for-pylint#2]
https://github.com/PatMyron/advent-of-code/runs/76468403

Difference between local/action output:
https://www.diffchecker.com/rk5wnHBB

**Comment by cclauss** [comment]
Thanks much for your feedback!

Please try setting __args__ to “__pip install -r requirements.txt ; pylint 2*__”,

PatMyron/advent-of-code#10

**Comment by cclauss** [comment]
In trying to come up with the right solution to #2, it is useful to understand what is required to get a proper pylint run on this project...

**Comment by cclauss** [comment]
What __pylint__ command did you use to get the local output?  See PatMyron/advent-of-code#9

**Comment by PatMyron** [comment]
Thanks! That worked. Closing in favor of https://github.com/cclauss/GitHub-Action-for-pylint/issues/1 since this works but a different default argument might make onboarding easier
